version: "3.2"

services:
  image-classification-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: rm-rfred/vit-worker:latest
    restart: always
    volumes:
      - /srv/docker/image-classification-worker/logs:/logs