# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_classification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aimage_classification.proto\x12\x14image_classification\"+\n\x1aImageClassificationRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"3\n\x18ImageClassificationReply\x12\x17\n\x0fpredicted_class\x18\x01 \x01(\t2\x9c\x01\n\x1aImageClassificationService\x12~\n\x18\x41pplyImageClassification\x12\x30.image_classification.ImageClassificationRequest\x1a..image_classification.ImageClassificationReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_classification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGECLASSIFICATIONREQUEST']._serialized_start=52
  _globals['_IMAGECLASSIFICATIONREQUEST']._serialized_end=95
  _globals['_IMAGECLASSIFICATIONREPLY']._serialized_start=97
  _globals['_IMAGECLASSIFICATIONREPLY']._serialized_end=148
  _globals['_IMAGECLASSIFICATIONSERVICE']._serialized_start=151
  _globals['_IMAGECLASSIFICATIONSERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
