# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_classification_pb2 as image__classification__pb2


class ImageClassificationServiceStub(object):
    """Service to perform image classification over image.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/classification.IMAGECLASSIFICATION/Detect',
                request_serializer=image__classification__pb2.ImageClassificationCandidate.SerializeToString,
                response_deserializer=image__classification__pb2.ImageClassificationResult.FromString,
                )


class ImageClassificationServiceServicer(object):
    """Service to perform IMAGECLASSIFICATION over image.
    """

    def Detect(self, request, context):
        """Determines the text on an input image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageClassificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=image__classification__pb2.ImageClassificationCandidate.FromString,
                    response_serializer=image__classification__pb2.ImageClassificationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'classification.IMAGECLASSIFICATION', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageClassificationService(object):
    """Service to perform image classification over image.
    """

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/classification.IMAGECLASSIFICATION/Detect',
            image__classification__pb2.ImageClassificationCandidate.SerializeToString,
            image__classification__pb2.ImageClassificationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
