# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_classification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image_classification.proto',
  package='classification',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aimage_classification.proto\x12\x0e\x63lassification\"-\n\x1cImageClassificationCandidate\x12\r\n\x05image\x18\x01 \x01(\x0c\")\n\x19ImageClassificationResult\x12\x0c\n\x04text\x18\x01 \x01(\t2z\n\x13IMAGECLASSIFICATION\x12\x63\n\x06\x44\x65tect\x12,.classification.ImageClassificationCandidate\x1a).classification.ImageClassificationResult\"\x00\x62\x06proto3'
)




_IMAGECLASSIFICATIONCANDIDATE = _descriptor.Descriptor(
  name='ImageClassificationCandidate',
  full_name='classification.ImageClassificationCandidate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='classification.ImageClassificationCandidate.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=53,
)


_IMAGECLASSIFICATIONRESULT = _descriptor.Descriptor(
  name='ImageClassificationResult',
  full_name='classification.ImageClassificationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='classification.ImageClassificationResult.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['ImageClassificationCandidate'] = _IMAGECLASSIFICATIONCANDIDATE
DESCRIPTOR.message_types_by_name['ImageClassificationResult'] = _IMAGECLASSIFICATIONRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageClassificationCandidate = _reflection.GeneratedProtocolMessageType('ImageClassificationCandidate', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECLASSIFICATIONCANDIDATE,
  '__module__' : 'image_classification_pb2'
  # @@protoc_insertion_point(class_scope:classification.ImageClassificationCandidate)
  })
_sym_db.RegisterMessage(ImageClassificationCandidate)

ImageClassificationResult = _reflection.GeneratedProtocolMessageType('ImageClassificationResult', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECLASSIFICATIONRESULT,
  '__module__' : 'image_classification_pb2'
  # @@protoc_insertion_point(class_scope:classification.ImageClassificationResult)
  })
_sym_db.RegisterMessage(ImageClassificationResult)



_IMAGECLASSIFICATION = _descriptor.ServiceDescriptor(
  name='IMAGECLASSIFICATION',
  full_name='classification.IMAGECLASSIFICATION',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=82,
  serialized_end=134,
  methods=[
  _descriptor.MethodDescriptor(
    name='Detect',
    full_name='classification.IMAGECLASSIFICATION.Detect',
    index=0,
    containing_service=None,
    input_type=_IMAGECLASSIFICATIONCANDIDATE,
    output_type=_IMAGECLASSIFICATIONRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGECLASSIFICATION)

DESCRIPTOR.services_by_name['IMAGECLASSIFICATION'] = _IMAGECLASSIFICATION

# @@protoc_insertion_point(module_scope)
